---
- hosts: webservers
  become: yes
  tasks: 
  - name: I want Insall jave in my Ununtu Nodes
    apt:
     name: "{{myjavapackageforubuntu}}"
     state: present
     when: ansible_os_family == "Debian"

  - name: I want Install java in RedHat Nodes
    apt:
     name: "{{java-1.8.0-openjd}}"
     state: present
    when: ansible_os_family == "RedHat"  