---
- hosts: webservers
  become: yes
  tasks: 
  - name: I wnat Install Webserver in My Ansible Nodes
    apt: 
     name: "{{mywebpackageforubuntu}}"
     state: present
  when: ansible_os_family == "Debian"

 

